### ISSUE TITLE
Add integer file size in bytes

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/rsteamshot#1]
To complement Rsteamshot::Screenshot#file_size, a new method #file_size_in_bytes would be nice. It should return an integer based on the #file_size string, parsed and converted to bytes.

**Comment by marcqualie** [comment]
@cheshire137 anyone assigned to this? Would love to take it as part of hacktoberfest

**Comment by cheshire137** [comment]
You're the first, @marcqualie! Go for it. 😀
